add util.py, modify config function
kenya-sk/CIP pull request #17
Opened 2017-09-06 10:02 UTC by kenya-sk

2017-09-06 12:37 UTC, MitsukiUsui requested changes
いい感じです。

2017-09-06 12:37 UTC, MitsukiUsui commented on util.py
> +#! /usr/bin/env python
俺が言ったのに申し訳ないが、util.pyだと標準ライブラリと勘違いするので、例えばciputil.pyとかの方がベターです。

2017-09-06 12:37 UTC, MitsukiUsui commented on util.py
> +    return basedir, level, output_video
get_level_configuration()を外したのはどういう理由ですか？

2017-09-06 12:37 UTC, MitsukiUsui commented on util.py
> +    return img
これも内部でfilepathを構築する方が親切じゃない？

2017-09-06 12:37 UTC, MitsukiUsui commented on draw_flow.py
> +    BASEDIR, LEVEL, OUTPUT_VIDEO = util.read_config(configFilepath)
いい感じです:)

2017-09-06 12:37 UTC, MitsukiUsui commented on util.py
> +    return img
あーbasedirがないとfilepathを構築できないのか

2017-09-06 12:37 UTC, MitsukiUsui commented on util.py
> +    return img
俺は, basedir, level, page, timeを引数として渡す関数の方が良いと思うけどどう思う？

2017-09-07 01:15 UTC, MitsukiUsui commented on util.py
> +    return img
basedirをciputil以外で必要になるケースが無いがするから、BASEDIRはciputil内のグローバル変数にするのはどうだろう。

2017-09-07 01:27 UTC, kenya-sk commented on util.py
> +    return basedir, level, output_video
勘違いです、分ける必要ありませんでした。変更しておきます。

2017-09-07 01:27 UTC, kenya-sk commented on util.py
> +    return img
そのほうが、綺麗な気がしますね。

2017-09-07 11:46 UTC, MitsukiUsui approved these changes

2017-09-07 11:46 UTC, merged