Fix mean
kenya-sk/CIP pull request #18
Opened 2017-09-08 10:55 UTC by kenya-sk

2017-09-08 14:07 UTC, MitsukiUsui reviewed
参考のため細かいコードの部分にコメントを書きました。

2017-09-08 14:07 UTC, MitsukiUsui commented on stabilize.py
> +    def calc_flow(prevImg, nextImg, prevFeature, lk_params):
この関数は、

1. featureを計算する 
2. imgとfeatureからsparseなflowを計算する

の2つの機能が混ざっているので、わかりにくいです。例えば引数としてprevFeatureが必要なのになぜnextFeatureがいらないのかなどが関数全文を読まないと分からない。もしきちんと切り分けたならば

1. get_feature(img, lk_params)
2. calc_flow(prevImg, prevFeature, nextImg, nextFeature)

になり、prevFeatureしか無い不自然さや、lk_paramsという怪しいパラメタの意味がなんとなくでも把握できるようになるはずです。

2017-09-08 14:07 UTC, MitsukiUsui commented on stabilize.py
> +            movement = np.array([meanX, meanY, meanZ])
自分しか使わない時もelseで変なcriterionが与えられた時にエラーをはくようにしておくことはなんだかんだ大事です。

2017-09-08 14:07 UTC, MitsukiUsui commented on stabilize.py
> +                meanZ = sum(flow[2])/len(flow[2])
meanX, meanY, meanZ = np.mean(flow, axis=1)　かな？

2017-09-08 14:07 UTC, MitsukiUsui commented on stabilize.py
> +            except ZeroDivisionError:
3つともexceptに入るのはflow.shape[1]==0のとき？？そしたらどのcriterianでもmeanX, meanY, meanZ = (0, 0, 0)でいい？

2017-09-08 14:07 UTC, MitsukiUsui commented on config/config.ini
> +VIDEO_FILEPATH = ./out/output_mode.mp4
どっちがどっちのFILEPATHかわかると良い。[stabilize]と[drawOpt]とかでセクションを分けてもいいかも。

2017-09-08 14:07 UTC, MitsukiUsui commented on stabilize.py
> +    prevFeature = cv2.goodFeaturesToTrack(prevGray, mask=None, **feature_params)
ここの1page目のprevFeatureの計算はcalc_flow内で行われる計算とは違うの？

2017-09-08 14:07 UTC, MitsukiUsui commented on stabilize.py
> +    def calc_movement(flow, criterion="mode"):
全体的にもっと短くできそう

2017-09-08 14:07 UTC, MitsukiUsui commented on stabilize.py
> +    def calc_movement(flow, criterion="mode"):
個人的にはmeanだけでも良い気がする。他のレベルでどうなるかも見てみたい。

2017-09-13 09:51 UTC, MitsukiUsui commented on stabilize.py
>              nextGood = nextFeature[status == 1]
Goodというのは何の略語？

2017-09-13 09:51 UTC, MitsukiUsui commented on stabilize.py
>              movement = np.array([modeX, modeY, modeZ])
このececptに入るのは入力がどういうときですか？

2017-09-13 13:45 UTC, MitsukiUsui commented on stabilize.py
> +            print("Error: criterion")
"BAD criterion: {}.  Select from \"mode\", \"median\", and \"mean\".".format(criterion)

2017-09-14 11:15 UTC, kenya-sk commented on stabilize.py
>              movement = np.array([modeX, modeY, modeZ])
入力配列の要素数が１つ以下の場合や連続値のような最頻値を求めることができない時です。

2017-09-20 13:22 UTC, MitsukiUsui requested changes

2017-09-20 13:22 UTC, MitsukiUsui commented on stabilize.py
> +    def calc_movement(flow, criterion="mode"):
どれでも動くんだよね？ならmasterにはmeanだけでmergeしましょう。

2017-09-20 13:22 UTC, MitsukiUsui commented on stabilize.py
>      fixDirection_arr[time] = (fixDirectionX, fixDirectionY, fixDirectionZ)
fixDirection_arr[page][time][xyz]にしたがってdocstring更新。

2017-09-20 13:22 UTC, MitsukiUsui commented on stabilize.py
>  OUTPUT_VIDEO = None
LEVELはciputil内に移動させてほしい。

2017-09-20 13:24 UTC, MitsukiUsui commented
fixDirection_arrの出力周りに関しては、このブランチのmarge後で大丈夫です。とりあえずmergeしよう。

2017-09-20 13:24 UTC, MitsukiUsui commented on stabilize.py
>  OUTPUT_VIDEO = None
取り急ぎなのでこれは後でも大丈夫！

2017-09-21 01:17 UTC, closed without merging