Issue20
kenya-sk/CIP pull request #41
Opened 2017-09-24 13:44 UTC by kenya-sk

2017-09-24 14:27 UTC, MitsukiUsui commented
prevFeatureを間違って使っています。

2017-09-24 14:28 UTC, MitsukiUsui requested changes

2017-09-24 14:28 UTC, MitsukiUsui commented on stabilize.py
> +    fixDirection_arr[page][time][xyz] = [1-PAGE_MAX+1][1-TIME_MAX+1](fixDirectionX, fixDirectionY, fixDirectionZ)
stupid

2017-09-24 14:28 UTC, MitsukiUsui commented on stabilize.py
> +        angle_arr = np.arctan2(sparseFlow[:, 0], sparseFlow[:, 1]) * 180 / np.pi
sparseFlow[:, 0]がなんなのかわかりにくい。

2017-09-24 14:28 UTC, MitsukiUsui commented on stabilize.py
> +                latestMovement = movement
latestMovementの更新は正常なときだけ行った方が直感的。

2017-09-25 06:23 UTC, MitsukiUsui requested changes

2017-09-25 06:23 UTC, MitsukiUsui commented on stabilize.py
> +                latestMovement = movement
movementの更新とlatesetMovementの更新はtryの最後に一緒に書いてください。

2017-09-25 06:23 UTC, MitsukiUsui commented on stabilize.py
> +    fixDirection_arr[page][time][xyz] = [1~PAGE_MAX][1~TIME_MAX](fixDirectionX, fixDirectionY, fixDirectionZ)
fixDIrection_arr[page][time] = fixDirectionX, fixDirectionY, fixDirectionZ 
(page: 1 ~ PAGE_MAX, time: 1 ~ TIME_MAX)

2017-09-26 13:15 UTC, kenya-sk commented
modify Issue20

2017-09-27 12:40 UTC, MitsukiUsui requested changes

2017-09-27 12:40 UTC, MitsukiUsui commented on stabilize.py
> +    angleThresh = 9000
configに移す

2017-09-27 12:40 UTC, MitsukiUsui commented on stabilize.py
> +    fixDirection_arr[page][time][xyz] = [1~PAGE_MAX][1~TIME_MAX](fixDirectionX, fixDirectionY, fixDirectionZ)
fixDIrection_arr[page][time] = fixDirectionX, fixDirectionY, fixDirectionZ 
(page: 1 ~ PAGE_MAX, time: 1 ~ TIME_MAX)

2017-09-27 12:40 UTC, MitsukiUsui commented on stabilize.py
> +    """
コメントアウトは削除

2017-09-27 12:40 UTC, MitsukiUsui commented on stabilize.py
> +                    raise FeatureError("Not detect feature")
ifの下にmovementの更新とlatestMovementの更新を持って来る

2017-09-27 13:08 UTC, kenya-sk commented
change!

2017-09-27 13:14 UTC, kenya-sk commented
動きました

2017-09-27 13:22 UTC, MitsukiUsui approved these changes

2017-09-27 13:22 UTC, merged