fixDirection_arr manage with config
kenya-sk/CIP pull request #42
Opened 2017-09-24 15:27 UTC by kenya-sk

2017-09-24 15:50 UTC, MitsukiUsui requested changes

2017-09-24 15:50 UTC, MitsukiUsui commented on config/config.ini
> +READ_FILEPATH = ./fixDirec.npy
一緒でいいです。
DUMP_FILEPATH

2017-09-24 15:50 UTC, MitsukiUsui commented on config/config.ini
> +READ_FILEPATH = ./fixDirec.npy
./out/fixDirec.npy

2017-09-25 04:33 UTC, kenya-sk commented
pull request Issue31

2017-09-25 06:24 UTC, merged