Issue 26
kenya-sk/CIP pull request #45
Opened 2017-09-25 04:53 UTC by kenya-sk

modify file path

2017-09-25 08:53 UTC, MitsukiUsui requested changes

2017-09-25 08:53 UTC, MitsukiUsui commented on dot_product.py
> +        imgSize_y = flow.shape[1]
hight = flow.shape[0]
width = flow.shape[1]
変数名に_を使うのは原則として型名が続くときのみにしてください。

2017-09-25 08:53 UTC, MitsukiUsui commented on dot_product.py
> +                                           np.dot(flow[x][y], flow[x+1][y+1])])
windowSizeは3*3でhard-codingしたのか。汎用性をあげたい。

2017-09-25 08:53 UTC, MitsukiUsui commented on dot_product.py
> +                                           np.dot(flow[x][y], flow[x+1][y+1])])
というかベクトル演算でできるはず。einsumとか使ってかけないかな？
http://www.procrasist.com/entry/einsum

2017-09-25 08:53 UTC, MitsukiUsui commented on dot_product.py
> +    dotProduct_arr = np.zeros((TIME_MAX + 1, 960, 960))
dotProductはflowに対して計算されるのだからTIME_MAX+1なのはおかしい。

2017-09-25 08:53 UTC, MitsukiUsui commented on dot_product.py
> +    dotProduct_arr = np.zeros((TIME_MAX + 1, 960, 960))
うーん。docProduct_arr[0]とdocProduct_arr[1]が0ベクトルか....

2017-09-25 08:53 UTC, MitsukiUsui commented on dot_product.py
> +    global OUTPUT_VIDEO
globalの必要がない。

2017-09-25 09:12 UTC, takebiolac commented on dot_product.py
> +    dotProduct_arr = np.zeros((TIME_MAX + 1, 960, 960))
これは合ってるはずなんだけど

2017-09-25 09:14 UTC, takebiolac commented on dot_product.py
> +                                           np.dot(flow[x][y], flow[x+1][y+1])])
windowSize を汎用的にしたいというのはわかるけど、内積の計算を縮約記法にする意味がわからない、どういう意図？

2017-09-25 13:42 UTC, takebiolac commented
pull request

2017-09-25 13:59 UTC, MitsukiUsui requested changes

2017-09-25 13:59 UTC, MitsukiUsui commented on dot_product.py
> +        flowMargin = np.zeros((imgSizeX + 2, imgSizeY + 2, 2))
assert flow.shape[0]==flow.shape[1]
width = flow.shape[0]
でwidth+2も別の変数に代入する（使う場所が複数あるため）

2017-09-25 13:59 UTC, MitsukiUsui commented on dot_product.py
> +    fixDirection_arr=np.load("./out/fixDir.npy")
config使ってください。

2017-09-25 13:59 UTC, MitsukiUsui commented on dot_product.py
> +            for yShift in range(-1, 2):
(-1, 0, 1)

2017-09-25 13:59 UTC, MitsukiUsui commented on dot_product.py
> +        dotProduct = np.min(dotProductNeighbor, axis=0)
元気な時に考えます。

2017-09-25 14:12 UTC, takebiolac commented
pull request

2017-09-26 08:21 UTC, takebiolac commented
cmlFlow と統合しました。

2017-09-27 13:56 UTC, takebiolac commented
done

2017-09-27 15:19 UTC, MitsukiUsui requested changes

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +        dotProductNeighbor = np.zeros ((10, heightMargin, widthMargin))
(heightMargin, widthMargin, 10)

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +        dotProductNeighbor = np.zeros ((10, heightMargin, widthMargin))
やっぱり今のままでいいです。

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +                    shifted[1 + xShift : height + xShift + 1, 1 + yShift : width + yShift + 1] = flow
shifted[1+xShift : 1+xShift+height, 1+yShift : 1 + yShift + width]
or
shifted[1+xShift : 1+height+xShift, 1+yShift : 1 + width + yShift]
しっくり来る方で。

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +    """
assert windowSize%2 ==1 
assert windowSize>=3

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +        dotProductNeighbor = np.zeros ((neighborNum, widthMargin, widthMargin))
これをforの直前に書く。

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +        widthMargin = width + margin*2 #two direction +, -
widthMargin = margin + width + margin

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +
この空白行いらない

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +
この空白行いらない

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +
no br

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +
no br

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +            dotImg = cv2.circle(dotImg, (x, y), 3, (255,0,0), -1)
assert reversePoint_arr.shape[0] == 2
for i in range(reversePoint_arr.shape[1]):

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +    windowSize, flowThreshold, dotThreshold, calcDotFlag, dumpFilepath, videoFilepath = ciputil.read_config_dot(configFilepath)
calcDotFlagよりrecalculate = True, Falseの方がわかりやすいかな？

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +        print("DONE: load dot product array")
print("DONE: load dot product array from {}".format(dumpFilepath))のみで良い

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +        print("DONE: load dot product array")
STARTとDONEに時間の差がないから

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +        reversePoint_arr = np.where(dotProduct_arr[time] < dotProductThreshold)
divisionPoint_arr

2017-09-27 15:19 UTC, MitsukiUsui commented on dot_product.py
> +            dotImg = cv2.circle(dotImg, (x, y), 3, (255,0,0), -1)
numPoints=reversePoint_arr.shape[1]としたらさらに親切かな？

2017-09-27 15:49 UTC, takebiolac commented
resolve

2017-09-27 15:56 UTC, MitsukiUsui requested changes

2017-09-27 15:56 UTC, MitsukiUsui commented on dot_product.py
> +        cmlFlow = cmlFlow_arr[time]
cmlFlowの実装が変わりました。

2017-09-27 15:56 UTC, MitsukiUsui commented on dot_product.py
> +
1 br is enough

2017-09-27 15:56 UTC, MitsukiUsui commented on dot_product.py
> +
no br

2017-09-27 15:56 UTC, MitsukiUsui commented on ciputil.py
> +    return  windowSize, flowThreshold, dotThreshold, calcDotFlag, dumpFilepath, videoFilepath
RECALCULATE

2017-09-27 15:56 UTC, MitsukiUsui commented on ciputil.py
> +    return  windowSize, flowThreshold, dotThreshold, calcDotFlag, dumpFilepath, videoFilepath
return recalculate, windowSize, flowThres, dotThres, dumpFilepath, videoFilepath

2017-09-27 16:01 UTC, merged